NOAA-GFDL/SIS2

SIS_tracer_advect.F90
ice_model.F90

issue #26
Missing OMP intent for a few variables cause sis2 not compiling with -openmp

Make SIS2 compile with -openmp

---

ice_model.F90

In AMIP mode, the model was crashing with a "snow being deposited on non-ice area" (or words to that effect).
This adds a check to avoid the thermodynamics and leave the specified ice concentration as is.

Update to avoid thermodynamics when using specified ice.

---

SIS_fast_thermo.F90
SIS_slow.F90
SIS_slow_thermo.F90
SIS_sum_output.F90
ice_model.F90

SIS2 dev/master does not compile with -openmp , which affects CM4 models.
This fixes the compilation issues. 
Note that a restart issue #42 exists regardless of the openmp and this fix.

Fix compilation issues with -openmp

---

SIS_slow_thermo.F90
ice_transport.F90

- Closes issue #49
- 1st issue
The crash in prod+openmp mode comes from a non-thread-safe subroutine call from within an OMP PARALLEL DO region.
The offending subroutine calls are advect_tracers_thicker() in ice_transport.F90.
This subroutine has a pointer inside (Tr) that could change unexpectedly from underneath a thread depending on an input argument.
The easy way to bypass the issue is to put the subroutine calls inside a OMP CRITICAL section (see below) which forces the threads
to pass through one at a time. Of course this is not the efficient way to fix the issue.
For an efficient fix we need to change the way the subroutine uses the pointer (Tr).
- 2nd issue
The crash with debug + openmp comes from another non-thread-safe block of code that allocates
some arrays inside a OMP …

Fixes two openmp issues #49

---

SIS_fast_thermo.F90

- FIA%sw_abs_ocn(i,j,k) is is being set in a loop k=0:ncat but is
declared with 1:ncat. The declaration has not changed but the
offending line was added recently. Other arrays set in the loop
are declared 0:ncat so the loop length is not incorrect.
Inspection of older code suggests a related line was copied from
a loop with k=1:ncat so the proposed fix emulates that.
- Run with debug executables using gnu, intel and pgi.
- Reproduces committed answers.

Fixes out-of-bounds index in SIS_fast_thermo.F90

---

SIS_slow.F90
ice_model.F90
ice_type.F90

The area_berg, mass_berg and ustar_berg are now updated in the icebergs_run call, which means that the icebergs_incr_mass subroutine does not need to be called from the SIS2 module.
With these changes, these fields can now be passed through the coupler.
In order to make this work, I had to define each field in both the ice_data_type and the ice_ocean_flux_type. This is a round about way of doing this, but I could not think of a better way, since the ice_data_type can not be seen by the update_icebergs routine.
Also, note that grid for the ice_ocean_boundary_type fields and ice_data_type fields must be the same for this to work. I hope this will not be a problem
Finally, note that I did notice that the value of the fields changes when the fields are passed through in the global model, …

Iceberg run call only

---

SIS_fast_thermo.F90

Fix for OpenMP in SIS_fast_thermo.F90
OMP directive was sharing isd,ied,jsd,jed instead of isc,iec,jsc,jec

 Fix for OpenMP in SIS_fast_thermo.F90

---

SIS_slow_thermo.F90

When SPECIFIED_ICE = True, the lines which copy fluxes from the FIA to IOF were being skipped despite slab ice optics being calculated. Thus, the underlying ocean effectively had no heat fluxes or liquid fluxes even where ice was not present because of the ice-ocean coupling.

Copy fluxes to ice ocean boundary when ice is specified

---

SIS_transport.F90

An if statement that checks if part_sz(i,j,k) <= 1.0 has been improved so that round off errors do not lead to category CatIce part_sz being inconsistent with excess cover.

Avoids round off errors when compressing

---

SIS2_ice_thm.F90
SIS_dyn_trans.F90
SIS_slow_thermo.F90
SIS_sum_output.F90
SIS_tracer_advect.F90
SIS_tracer_flow_control.F90
SIS_tracer_registry.F90
ice_age_tracer.F90
ice_grid.F90
ice_model.F90

- The treatment of passive ice tracers in SIS2 has been updated to better follow the movement of ice across and within thickness categories.
- Passive ice tracers should be four dimensional (i,j,ncat,nlevels)
- Ice-snow and Ice-ocean boundary conditions for passive tracers can be set
- Passive tracer stock calculation mirrors MOM6 more closely
These changes do not affect answers in Baltic and Baltic_ALE_z
To be done:
Design a pseudo-salt tracer that mimics the salinity tracer in SIS2

Passive tracers in slow thermodynamics routines

---

SIS_slow_thermo.F90
SIS_tracer_flow_control.F90
SIS_tracer_registry.F90
ice_age_tracer.F90

After conversations with @Hallberg-NOAA , we agreed that the portions of SIS2_thermodynamics that exposed elements of the TrReg to the routine could be pulled out. Here, three new routines were added to SIS_tracer_registry.F90 that handle the packing/unpacking of slices from 4d tracer arrays.

Update to https://github.com/NOAA-GFDL/SIS2/pull/64

---

src/SIS2_ice_thm.F90
src/SIS_continuity.F90
src/SIS_debugging.F90
src/SIS_diag_mediator.F90
src/SIS_dyn_bgrid.F90
src/SIS_dyn_cgrid.F90
src/SIS_dyn_trans.F90
src/SIS_fast_thermo.F90
src/SIS_fixed_initialization.F90
src/SIS_optics.F90
src/SIS_slow_thermo.F90
src/SIS_sum_output.F90
src/SIS_tracer_advect.F90
src/SIS_tracer_flow_control.F90
src/SIS_tracer_registry.F90
src/SIS_transport.F90
src/combined_ice_ocean_driver.F90
src/ice_age_tracer.F90
src/ice_model.F90

The name "mod" had been used for various module name variables throughout the
MOM6 code, but this can cause name-space conflicts with the mod intrinsic
function, so "mod" has been renamed "mdl" throughout the MOM6 code.  All answers
are bitwise identical.

Renamed variables "mod" to "mdl"

---

src/SIS_slow_thermo.F90

Added new diagnostics of the net ice melt, using both the self-explanatory
name net_melt and the CMOR standard name fsitherm.  All answers are bitwise
identical, but there are new entries in the SIS.available_diags files.

+Added ice_melt and fsitherm diagnostics

---

src/SIS_debugging.F90
src/SIS_dyn_bgrid.F90
src/SIS_dyn_cgrid.F90
src/SIS_dyn_trans.F90
src/SIS_fast_thermo.F90
src/SIS_fixed_initialization.F90
src/SIS_slow_thermo.F90
src/SIS_sum_output.F90
src/SIS_tracer_advect.F90
src/SIS_transport.F90
src/ice_model.F90

Moved the logging of runtime parameters used only for debugging into
SIS_parameter_doc.debugging, by adding the debuggingParam flag to their
get_param calls.  This is only applied to parameters whose values do not alter
the solutions, if the model is working properly, so the SIS_parameter_doc.all or
SIS_parameter_doc.short are still sufficient to exactly reproduce a simulation.
All answers are bitwise identical, but the SIS_parameter_doc files change in
MOM6_examples.

+Log debugging params to SIS_param_doc.debugging

---

src/ice_type.F90

Added a new element, stress_mag, with the time-mean of the magnitude of the
wind stresses at tracer points, to the publicly visible ice_data_type.  It is
not yet being allocated or used, so all answers are bitwise identical.

Added stress_mag to ice_data_type

---

src/ice_model.F90

- This update avoids a crash by masking the part_size that is read from restart (as is already done for mH_ice). It also ensures that pasrt_size adds up to 1 on land points to pass the SIS2 checks at initialization.
The long story is:
- A model with AM4+slab_ocean+SIS2 runs into a restart issue when DO_ICE_RESTORE is set to True
The model crashes after any restart with "NaN in input field of reproducing_sum(_2d)" pointing
to a NaN in checksum for freshwater diagnostics in SIS_sum_output.F90 line 511.
Runing with debugger shows that for some reason IST%part_size=1 for category k=3 at some land points
on the map where h_ice=0 and model crashes because of division by zero
(before the model hits the NaN in chesksum issue of the prod mode).
The bad points of IST%part_size=1 on land (mask=0) …

Fix NaN after a restart when DO_ICE_RESTORE=True

---

src/SIS_slow_thermo.F90
src/ice_model.F90

Fix the ice restoring issues
- This update addresses two independent issues with the ice restoring mechanism:
1. SM4p model blows up with too much ice when it tries to do ice restoring to climatology.
This only happens when SIS1 is replaced by SIS2.
Upon investigation I found that the algorithm in SIS_slow_thermo.F90 has an update ordering issue.
At the point when qflx_res_ice is calculated it updates the heat input to ice through bheat.
But this does not to have an immediate direct effect on the ice thickness
and its effect is delayed till the next timestep through other fluxes (flux_sh_ocn_top).
This leads to a runaway increasing of the ice thickness (wrong feedback).
To get around this we can increase bmelt instead of bheat which will decrease the ice thickness
subsequently in the same …

Fix ice restore issues

---

src/SIS_slow_thermo.F90
src/ice_model.F90

Eliminated the obsolete interfaces to the sea-ice that were used by the Verona
and older versions of the FMS coupler.  Specifically, the publicly visible
routines update_ice_model_slow_dn and update_ice_model_slow_up were eliminated,
the default value for the Verona_coupler argument was changed from true to false
with a fatal error if it is set to true, and several unused arguments were
eliminated from set_ocean_top_dyn_fluxes.  All answers are bitwise identical,
but one logged variable is eliminated from SIS_parameter_doc.layout.

+Remove the old Verona sea-ice coupling interfaces

---

src/SIS_sum_output.F90

This patch increases the precision of the coverage area in seaice.stats
from 13 to 17 digits.  This change will capture the full precision of
the variable, and will allow for more precise regression testing.
Coupled with this MOM6 PR:
https://github.com/NOAA-GFDL/MOM6/pull/962
and Gaea PR:
https://gitlab.gfdl.noaa.gov/ogrp/Gaea-stats-MOM6-examples/merge_requests/10

High precision sea ice area stats

---

src/SIS_slow_thermo.F90

salt_to_ice already includes the IST%part_size factor at line 1197.
This extra factor (with an effectively out of bound k=ncat+1) causes the ice limiting simulations (sm4p1) to crash for some processor layouts with:
FATAL from PE   812: NaN in input field of reproducing_sum(_2d).
where the reproducing_sum refers to the ice salinity.
I verified that this mod fixes the issue with sm4p1 and luckily reproduces the answers for the layouts that did work before the fix.

Bug fix for do_ice_limit

---

src/ice_model.F90

- Variable Ice%sCS%OSS%SST_C is not an ice state and hence is not in ice_model.res.nc
However for SPECIFIED_ICE=True it should be updated after restart, otherwise the model
would have a restart issue #107 
In specified ice this variable is read from data_table every time step. So that is also
the easiest way to update it after a restart.
- This update resolves issue #107 .
- This update also addresses issue #101 by adding some indication 
that SIS2 is being restored from restart files.
Currently with input_filename being 'n' or 'r'  having no effect, there is no
indication in stdout whether restart files are being read or not.
This would make it a little easier to debug restart issues.

Fix for specified ice restart issue #107

---

src/SIS_continuity.F90
src/SIS_ctrl_types.F90
src/SIS_debugging.F90
src/SIS_diag_mediator.F90
src/SIS_dyn_bgrid.F90
src/SIS_dyn_cgrid.F90
src/SIS_dyn_trans.F90
src/SIS_fast_thermo.F90
src/SIS_fixed_initialization.F90
src/SIS_hor_grid.F90
src/SIS_slow_thermo.F90
src/SIS_sum_output.F90
src/SIS_tracer_advect.F90
src/SIS_tracer_registry.F90
src/SIS_transport.F90
src/SIS_types.F90
src/SIS_utils.F90
src/ice_age_tracer.F90
src/ice_model.F90
src/ice_type.F90
src/slab_ice.F90
src/specified_ice.F90

Added dimensional consistency testing capabilities to SIS2, analogous to those
that have been developed for MOM6.  Specifically, these test consistency in time
and length units.  All answers are bitwise identical, and no bugs have been
identified, but there are new arguments to some interfaces and a number of
arguments or elements of types have units that can be dimensionally rescaled.
SIS2 commits with this PR include:
- NOAA-GFDL/SIS2@f803d26 Minor changes to increase similarity to dev/gfdl
- NOAA-GFDL/SIS2@4fdb2a4 +Rescaled velocities in the simple_OSS_type
- NOAA-GFDL/SIS2@132a1c6 Code rescaling simplification and clean-up
- NOAA-GFDL/SIS2@53217dc +Rescaled some internal timestep variables
- NOAA-GFDL/SIS2@40ee0ec +Rescaled IOF%flux_u_ocn and IOF%stress_mag
- NOAA-GFDL/SIS2@8481061 …

SIS2: Dimensional consistency testing for time and lengths

---

src/SIS_types.F90

Avoid reporting any sea-ice values that fail the ice bounds checks for points
that have been masked out as land.  Without this, huge numbers of uninformative
reports were being issued about improper sums of the part_size arrays with some
coupled model configurations with masked processors.  All answers are bitwise
identical.

Avoid sea-ice bounds checks over land

---

src/SIS2_ice_thm.F90
src/SIS_continuity.F90
src/SIS_debugging.F90
src/SIS_diag_mediator.F90
src/SIS_dyn_bgrid.F90
src/SIS_dyn_cgrid.F90
src/SIS_dyn_trans.F90
src/SIS_fast_thermo.F90
src/SIS_fixed_initialization.F90
src/SIS_optics.F90
src/SIS_slow_thermo.F90
src/SIS_sum_output.F90
src/SIS_transport.F90
src/combined_ice_ocean_driver.F90
src/ice_age_tracer.F90
src/ice_grid.F90
src/ice_model.F90
src/specified_ice.F90

Removed hard-coded newline symbols from most SIS2 parameter descriptions in
calls to get_param or log_param, instead allowing these routines to format the
output automatically.  All answers are bitwise identical, but there are changes
in many of the variable descriptions in the SIS_parameter_doc files.

SIS2: +Remove carriage returns in parameter descriptions

---

src/SIS_ctrl_types.F90
src/SIS_ice_diags.F90
src/SIS_slow_thermo.F90
src/SIS_state_initialization.F90
src/SIS_types.F90
src/ice_model.F90
src/ice_spec.F90

This group of commits adds several new options for initializing the state of
the sea ice, refactors related parts of the code for simplicity or cleanliness,
and makes a public interface more consistent with other SIS2 code.  There are
some atypical configurations in which answers could change at roundoff due to
changing order of arithmetic.  All answers in the MOM6-examples test cases are
bitwise identical, and there are new entries in the SIS_parameter_doc files. The
commits in this PR include:
- NOAA-GFDL/SIS2@e00bf47 +Use SIS_state_initialization for initialization
- NOAA-GFDL/SIS2@8fd108f +Added SIS_state_initialization.F90
- NOAA-GFDL/SIS2@7c04797 Initialized IST%t_surf to 0 deg C in Kelvin
- NOAA-GFDL/SIS2@d1146ba +Rescale thickness in rescale_ice_state_rest_files
- …

SIS2: +(*)Add sea ice initialization options

---

src/SIS_slow_thermo.F90
src/SIS_state_initialization.F90
src/SIS_sum_output.F90
src/SIS_types.F90
src/ice_model.F90

Added the new option to transmute sea ice and snow into sea water as a simple
form of outflow open boundary condition.  Also cleaned up some problems with
non-reproducing SIS_parameter_doc files.  There are new runtime options and
entries in the SIS_parameter_doc files, but all answers in the existing
MOM6-examples test suite are bitwise identical.  The commits in this PR include:
- NOAA-GFDL/SIS2@d5e7883 +Added TRANSMUTE_ICE option
- NOAA-GFDL/SIS2@acc8a6c +Corrected description of ICE_THICKNESS_INIT_CONFIG

SIS2: +Add transmute ice outflow open boundary condition

---

src/SIS_dyn_trans.F90
src/SIS_optics.F90
src/SIS_tracer_advect.F90
src/SIS_transport.F90
src/combined_ice_ocean_driver.F90
src/ice_model.F90

Updated the default values for CGRID_ICE_DYNAMICS (to "C") and
INCONSISTENT_COVER_BUGS and CFL_MASS_NEGLECT_BUG to false, and made the
documented units of MIN_POND_FRAC and MAX_POND_FRAC consistent across the SIS2
code.  In addition, component arguments were added to the close_param_file calls
so that the parameter file defaults are properly documented.  By design, all
solutions in the MOM6-examples test suite are bitwise identical, but answers can
change for other cases, and there are changes in the SIS_parameter_doc files.

(*)Updated SIS2 parameter defaults

---

src/SIS_types.F90
src/ice_model.F90
src/ice_type.F90

Improved the SIS2 checksum capabilities that are triggered when DEBUG=True,
especially when debugging restarts.  Some variables that should not necessarily
reproduce are not longer being reported, while other types that do need to
reproduce are being checked.  These changes include the new subroutines
OSS_chksum and TSF_chksum, along with new optional arguments to IOF_chksum and
Ice_public_type_chksum.  Also, the albedos and absorbed radiation diagnostics
are now being set to 0 in categories with 0 part size, whereas they had
previously just retaine their previous value; this does not change answers but
it does make debugging easier.  All answers and output files are unchanged.

+Improve SIS2 checksum capabilities for debugging

---

src/SIS_diag_mediator.F90

- Add domain position arguments to diag_axis_init calls
diag_axis_init has a new optional argument to specify the corner location of the diagnostics on the grid.
Although these are optional args the model would crash if it sends such corner diagnostics without passing the appropriate optional argument to diag_axis_init.

This is the minimum update required to use 2020.01 FMS and coupler

---

src/SIS_continuity.F90
src/SIS_dyn_trans.F90
src/SIS_ice_diags.F90
src/SIS_state_initialization.F90
src/SIS_transport.F90
src/ice_model.F90

This PR adds new runtime parameters to restrict the transport out of cells
with miniscule ice masses and to prevent the formation of very small fractional
ice coverage in some categories. These options should help avoid some problems
that had been arising with tracer transport in and around categories with tiny
masses.  There were also some minor changes to help detect unused parameters. 
By default there are no changes to answers, but there are new entries in
SIS_parameter_doc files.  The commits in this PR include:
- NOAA-GFDL/SIS2@9adb8fe Always call ice_state_mass_init
- NOAA-GFDL/SIS2@e431d16 +Added new runtime parameter ICE_COVER_DISCARD
- NOAA-GFDL/SIS2@c44f798 +Added CONTINUITY_H_NEGLECT to mask tiny fluxes

SIS2: +Add options to restrict tiny ice transports

---

src/SIS_sum_output.F90

Revised SIS_sum_output.F90 to merge all blocking global sums in SIS2 that are
used routinely into a single blocking sum in SIS_sum_output for improved model
efficiency.  Also removed unneeded variables from the SIS_sum_out_CS and
reformatted the module use statements in this module.  All answers are bitwise
identical.

Combine all global sums in SIS_sum_output

---

src/SIS_dyn_trans.F90
src/combined_ice_ocean_driver.F90

Replace calls to mpp_clock routines from mpp_mod with calls to cpu_clock from
the module MOM_cpu_clock, to limit the direct use of fms routines and expand the
standardized use of the MOM6 infrastructure.  Also corrected the granularity of
two of the sea-ice clocks, to avoid double counting with clocks at the same
level of granularity, and added clocks around calls that to dierctly exchange
information between the ice and ocean.  All answers are bitwise identical.

Use MOM6 cpu_clock timers in place of mpp_clock

---

src/SIS_types.F90
src/ice_model.F90

Cleaned up the logic for when to reset the ocean albedo, and split the single
internal interface for set_ocean_albedo into set_ocean_albedo_from_astronomy and
set_ocean_albedo_from_coszen.  Also removed the element frequent_albedo_update
from the ice_rad_type, as it is no longer used.  Also cleaned up the module use
statements at the top of ice_model.F90 and SIS_types.F90, alphabetizing entries
and removing references to unused routines and types.  All answers are bitwise
identical.

+Simplified the logic about setting ocean albedos

---

src/SIS_ctrl_types.F90
src/SIS_dyn_bgrid.F90
src/SIS_dyn_cgrid.F90
src/SIS_dyn_trans.F90
src/SIS_framework.F90
src/SIS_hor_grid.F90
src/SIS_state_initialization.F90
src/SIS_tracer_flow_control.F90
src/SIS_types.F90
src/combined_ice_ocean_driver.F90
src/ice_age_tracer.F90
src/ice_boundary_types.F90
src/ice_model.F90
src/ice_ridge.F90
src/ice_spec.F90
src/ice_type.F90

Added the new module SIS_framework with interfaces to some FMS infrastructure
routines and direct infrastructure calls from throughout the SIS2 code either
through this new module or the MOM6 framework directory.  All calls ultimately
lead to the same code as before, but this should help to prevent ongoing changes
to FMS from requiring widespread changes in the SIS2 code and should in ensuring
continuity of answers as FMS evolves.  All answers and output files are bitwise
identical, but there are some new interface names and one new optional argument.
The commits in this PR include:
- NOAA-GFDL/SIS2@6b1f497 Access infrastructure routines via SIS_framework
- NOAA-GFDL/SIS2@9b73944 Use broadcast_domain in share_ice_domains
- NOAA-GFDL/SIS2@4de49b9 Use SIS_framework in …

SIS2: +Encapsulate SIS2 infrastructure calls

---

src/ice_type.F90

Added code to use the optional init_call argument to ice_data_type_chksum,
which was recently omitted when this optional argument was added in an attempt
to partially address SIS2 issue #102.  Without this change, the logical variable
init was being used but not set, so it would have been random whether some of
the chksums were being written.  All solutions are bitwise identical.

Use init_call argument to ice_data_type_chksum

---

src/SIS_state_initialization.F90

CM4 highres in Interspersed Ice mode crashes when there is no ice_model.res.nc 
The crash happens on the two  calls to data_override_unset_domains on lines 155 and 315 because
data_override is not initialized yet **on the fast ICE cores** that these ice calls run on.
I verified that this update fixes the issue.

Fix data_override crash in interspersed ice mode

---

src/SIS_continuity.F90
src/SIS_ctrl_types.F90
src/SIS_diag_mediator.F90
src/SIS_dyn_bgrid.F90
src/SIS_dyn_cgrid.F90
src/SIS_dyn_trans.F90
src/SIS_fast_thermo.F90
src/SIS_fixed_initialization.F90
src/SIS_framework.F90
src/SIS_ice_diags.F90
src/SIS_slow_thermo.F90
src/SIS_state_initialization.F90
src/SIS_sum_output.F90
src/SIS_tracer_flow_control.F90
src/SIS_transport.F90
src/SIS_types.F90
src/ice_age_tracer.F90
src/ice_boundary_types.F90
src/ice_model.F90
src/ice_ridge.F90
src/ice_type.F90
src/slab_ice.F90

Restructured the SIS2 code so that all calls related to restarts and other
infrastructure calls are directed via the SIS_framework module, in preparation
for the transparent support of both the FMS1 and FMS2 i/o interfaces.  There are
a number of new public interfaces, notably in SIS_framework.F90 and there are
widespread changes, mostly related to these new interfaces, but no algorithms
are changed in any way, and all answers and output files are bitwise identical.
The commits in this PR include:
- NOAA-GFDL/SIS2@e9c96df +Access coupler_types via SIS_framework
- NOAA-GFDL/SIS2@7d10fd6 Add FMS2_io non-implementation error messages
- NOAA-GFDL/SIS2@6bcd45e Specify dimensions in register_restart_field calls
- NOAA-GFDL/SIS2@0e7a5ba +Add option to specify that restarts use FMS2
- …

+SIS2: Restructure SIS2 to use the framework module

---

src/SIS_ctrl_types.F90
src/SIS_diag_mediator.F90
src/SIS_framework.F90
src/SIS_slow_thermo.F90
src/SIS_state_initialization.F90
src/SIS_types.F90
src/combined_ice_ocean_driver.F90
src/ice_spec.F90
src/ice_type.F90

This PR contains a series of commits that coordinate the SIS2 infrastructure
calls with the MOM6 infrastructure calls and make calls to the underlying FMS
infrastructure via that MOM6 framework or config_src/infra modules.  All answers
and output are bitwise identical, but there are some interface changes, and the
version of MOM6 that is used must include the changes in MOM6 PR #1363 to
dev/gfdl (merged in on April 6, 2021).  The changes in this PR include:
- NOAA-GFDL/SIS2@b10799c Use EAST_FACE instead of EAST to denote positions
- NOAA-GFDL/SIS2@27d462a Eliminate unused module use entries
- NOAA-GFDL/SIS2@3e342e9 Use MOM6/config_src/infra in SIS_framework.F90
- NOAA-GFDL/SIS2@6b24054 Call data_override via MOM_data_override
- NOAA-GFDL/SIS2@783f937 +Use same_domain from MOM_domain_infra …

SIS2: Revise the SIS2 use of framework code

---

src/SIS_ctrl_types.F90
src/SIS_diag_mediator.F90
src/SIS_framework.F90
src/SIS_slow_thermo.F90
src/SIS_state_initialization.F90
src/SIS_types.F90
src/combined_ice_ocean_driver.F90
src/ice_model.F90
src/ice_spec.F90
src/ice_type.F90

Revised the handling of the SIS2 namelist entries so that they are no longer
ignored, addressing SIS2 issue #96.  This includes modification so that the
behavior when input_filename = 'F' is exactly the same as if it is 'n' if there
are no restart files in the restart_input_dir, or as if it is 'r' if the restart
files are there.  Previously there had been differences in the output files
generated, but the solutions were always if input_filename = 'F'.  The entries
in dirs%restart_output_dir are now used to guide where SIS2 writes its restarts,
whereas this had previously been ignored with the output always going into
"./RESTART/".  As a part of this change, a 5 routines have been imported from
MOM_restart.F90 to help determine when this is a new run in 'F' mode, and there
have been a …

(*)+Stop ignoring SIS2 namelist entries

---

src/SIS_restart.F90

This PR contains a small handful of commits that revise the SIS2 restart
capability to read and write without using any FMS routines directly, which
enables the migration to use the new FMS2 I/O interfaces while still maintaining
the ability to run with the traditional FMS I/O interfaces.  All solutions are
bitwise identical when used with either of the MOM6 config_src/infra directories
(although there are some changes in the output file metadata), and the SIS2 runs
in MOM6-examples with the new restart files reproduce answers when either I/O
via the root PE or parallel I/O are used.
This SIS2 PR requires the use of MOM6 code with the changes in https://github.com/NOAA-GFDL/MOM6/pull/1373 .
The commits in this PR include:
- NOAA-GFDL/SIS2@0b80b63 Corrected call to open_file in …

SIS2: Revise SIS2 restart capability

---

src/SIS_ctrl_types.F90
src/SIS_ice_diags.F90
src/SIS_slow_thermo.F90
src/SIS_types.F90

Added 4 new diagnostics to comply with CMOR requirements for units and how the
diagnostics are calculated.  Because the suggested CMOR names were already in
use, they have been added with _CMOR appended to their names.  The four new
diagnostics in question are "siconc_CMOR", "sivol_CMOR", "sisnconc_CMOR" and
"sitemptop_CMOR", and of course there are new entries in the SIS.available_diags
files.  This PR closes SIS2 issues #91, #92, and #93.  In addition by making the
axes in the registration call for "RDG_FRAC" consistent with the dimensionality
of the diagnostic that is written out, this PR might also have addressed SIS2
issue #138.  The new diagnostics have been visually confirmed to be credible,
and all solutions are bitwise identical.

+Added 4 new diagnostics to comply with CMOR

---

src/SIS_tracer_registry.F90
src/SIS_transport.F90

Changed the interface to set_massless_SIS_tracers by replacing the optional
compute_domain logical argument (which took the opposite sense of what its name
seems to imply) with a new optional integer argument, halos, to specify the
size of the halos that this works on.  Previously calls to this routine from
ice_cat_transport and finish_ice_transport had led to uninitialized data being
used, but this change fixes this problem.  All answers are bitwise identical,
although there is a change to a public interface.

+Change opt. arg. to set_massless_SIS_tracers

---

src/SIS2_ice_thm.F90

This patch updates the equation of state (EOS) calls in SIS2 to use the
updated MOM EOS API:
* `EOS_end` is removed, since there is no longer anything to deallocate
* THE EOS type is allocated prior to calling `EOS_init`, rather than
relying on the internal allocation.  This is because `EOS_init` no
longer expects a pointer, and no longer does this allocation.
This patch may still work with the older version of MOM6, although the
EOS pointer will be double-allocated.

MOM EOS pointer API update

---

src/SIS_ctrl_types.F90
src/SIS_dyn_cgrid.F90
src/SIS_dyn_trans.F90
src/SIS_fast_thermo.F90
src/SIS_hor_grid.F90
src/SIS_ice_diags.F90
src/SIS_slow_thermo.F90
src/SIS_state_initialization.F90
src/SIS_sum_output.F90
src/SIS_types.F90
src/ice_age_tracer.F90
src/ice_grid.F90
src/ice_model.F90
src/ice_type.F90

Use the allocate call's source optional argument to initialize 145 arrays in
14 files.  This change simplifies and shortens the code and will make it easier
to identify uninitialized allocated arrays.  This change was only made to arrays
that were already being initialized on the same line as the allocate or shortly
thereafter.  All answers are bitwise identical.

Use allocate with source to initialize arrays

---

src/SIS_ctrl_types.F90
src/SIS_hor_grid.F90
src/SIS_transcribe_grid.F90

Rescaled the units of the Rad_Earth element of SIS_hor_grid_type and set it
using the equivalently scale variable dG%Rad_Earth_L from the dyn_grid type.
This change led naturally to changed units for the I_area_Earth internal
variable in ice_diagnostics_init() and the cancellation of some grid rescaling
factors that were there before.  This commit requires that SIS2 use a recent
(November 27, 2021 or later) version of MOM6 from the dev/gfdl branch, and will
not compile with earlier versions of the MOM6 code.  All answers are bitwise
identical, but there is one minor interface change in a widely used transparent
type.

+Rescale G%Rad_Earth and set it via dG%Rad_Earth_L

---

src/SIS_sum_output.F90

Corrected several dimensional consistency or dimensional documentation issues
in SIS_sum_output.F90, and generally simplified the summed output code:
- Corrected the documented units of a several salt content variables
- Corrected the magnitude of the diagnostic salt content stocks written to
stdout, which had been off by 3 orders of magnitude (i.e., were in tons of
salt) relative to what might have been expected (kg of salt).
- Consolidated the dimensional rescaling factors into just 3 variables for the
rescaling of areas, area integrated masses, and area integrated heat
- Introduced separate variables for the cell-area integrated heat, water and
salt inputs in mks units to differentiate them from the dimensionally
rescaled variables used to accumulate column inputs per unit area
- …

(*)Correct SIS summed output, including salt units

---

src/SIS2_ice_thm.F90
src/SIS_dyn_trans.F90
src/SIS_fast_thermo.F90
src/SIS_types.F90
src/ice_model.F90
src/ice_type.F90

Revised ice_stock_pe() to report the heat stock relative to liquid water at 0
degrees C, rather than just the heat required to melt the ice, as this gives a
much more robust estimates of the enthalpy budget when sea ice salinities are
allowed to vary.  To help implement this, the new function energy_0degC was
added to SIS2_ice_thm.F90.  Several module use statements that were referring to
unused routines from within SIS2_ice_thm were also redacted.  All solutions are
bitwise identical, but there are changes in the reported stock values, and there
is a new publicly visible function.

+(*)Report heat stocks relative to liquid at 0 degC

---

src/SIS2_ice_thm.F90
src/SIS_continuity.F90
src/SIS_ctrl_types.F90
src/SIS_debugging.F90
src/SIS_diag_mediator.F90
src/SIS_dyn_bgrid.F90
src/SIS_dyn_cgrid.F90
src/SIS_dyn_trans.F90
src/SIS_fast_thermo.F90
src/SIS_hor_grid.F90
src/SIS_ice_diags.F90
src/SIS_optics.F90
src/SIS_restart.F90
src/SIS_state_initialization.F90
src/SIS_sum_output.F90
src/SIS_tracer_advect.F90
src/SIS_tracer_registry.F90
src/SIS_transport.F90
src/SIS_types.F90
src/SIS_utils.F90
src/ice_boundary_types.F90
src/ice_model.F90
src/ice_ridge.F90
src/ice_shortwave_dEdd.F90
src/ice_type.F90
src/slab_ice.F90
src/specified_ice.F90

This PR includes a series of commits that correct the unit documentation for
43 variables, correct numerous spelling errors in comments widely scattered
throught the SIS2 code, and revises the comments in SIS_tracer_advect.F90 to
reflect the fact that SIS2 never makes the Boussinesq approximation.  Only
comments are changed and all answers are bitwise identical.
The SIS2 commits that are included in this update are:
- NOAA-GFDL/SIS2@d18605e Fixed 15 more variable unit descriptions
- NOAA-GFDL/SIS2@41c76d8 Corrected spelling errors in comments
- NOAA-GFDL/SIS2@98e926e Corrected comments in SIS_tracer_advect.F90
- NOAA-GFDL/SIS2@dde02fb Fixed 28 variable unit descriptions

Correct variable unit descriptions

---

src/SIS_sum_output.F90

In merging in two separate pull requests that made corrections to similar
lines in the same file, three renamed variables retained their original names,
resulting in SIS2 code that does not compile.  Each of the PRs was fully tested
separately, but for whatever reason their combination was not, and the SIS2 git
repository does not seem to detect certain merge conflicts.  This PR updates
these variable names to their intended values, and the code is once more
compiling and is reproducing the intended outputs.
This PR will address SIS2 issue #167, which can be closed once this PR is accepted.

Fix the result of a bad automated merge

---

src/ice_type.F90

- CM4/ESM4 coupled models get loads of warnings in stdout (causing 2G
fms.out files per year) like:
WARNING from PE   704: Bad ice data End set_ice_surface_state ;  at   20.2   6.5 or i,j,k =    5   5   0; nbad =    240 on pe  704 ; T_sfc =   0.0000E+00, ps =   1.0000E+00, S_sfc =   0.0000E+00
- This is because t_surf is set to 0 after allocation and then compared
with a minimum 273.15-100 (K) to catch bad surface values over sea ice
but the comparison is not restricted to ocean and is causing warnings
over land in fully coupled models.
- The fix is to restrinct the comparison over ocean mask just like is
done in SIS_types.F90

Fix Bad ice warnings over land

---

src/SIS_open_boundary.F90

The most recent PR to SIS2 includes MOM_memory.h in one of its files,
which breaks certain SIS2-only library builds.
This patch replaces it with SIS2_memory.h, which is functionally
identical but plays better with existing builds.

Replace MOM_memory.h with SIS2_memory.h

---

src/SIS_dyn_bgrid.F90
src/SIS_dyn_cgrid.F90
src/SIS_dyn_trans.F90
src/SIS_types.F90
src/ice_model.F90
src/ice_type.F90
src/specified_ice.F90

Modified the syntax of the logical comparisons with the various mask2d
variables to always check whether they are larger than 0.0, not 0.5 and use
similar syntax throughout the SIS2 code.  Because these arrays are always either
0.0 or 1.0, the answers are bitwise identical.

Standardize syntax in mask2d logical tests

---

src/SIS_slow_thermo.F90
src/ice_model.F90
src/ice_spec.F90

This PR addresses two different unrelated issues (my apologies for combining them, but they are in use together in ESM4.5):
- 1. The new whitecaps albedo scheme of Dunne et.al. needs the u,v fluxes be passed to ice_param/compute_ocean_albedo. It is now possible to request SIS2 doing that since ice_param is already updated to accept those optional arguments.
- 2. There is a restart issue (1x2days .ne. 2x1days) for the specified-ice option of SIS2. With this fix, it is possible to use SIS2 in AM4/AM5 experiments (which till now have been using SIS1) and hence the same executable for running AM and CM models. The fix is basically to un-comment what @Hallberg-NOAA has already put in line 2408 of ice_model.F90 plus an addition to bypass recategorize_ice for specified-ice.

Fix specified ice restart issue AND add flux_u,flux_v optional args to compute_ocean_albedo

---

src/SIS_dyn_bgrid.F90
src/SIS_dyn_cgrid.F90
src/SIS_dyn_trans.F90
src/SIS_restart.F90
src/SIS_types.F90
src/ice_grid.F90
src/ice_model.F90
src/ice_ridge.F90

Revised the SIS2 code so that the output restart files are always exactly the
same as they would be if no dimensional rescaling is applied.  The input restart
files can still have rescaling, so files written by previous versions of the
code still work exactly as before.  This does change the output, in the sense
that the restart files are unscaled and some units documents in the restart
files are corrected, but the solutions themselves are bitwise identical. Also,
there are new (non-optional) unit scaling type arguments to several routines.
The specific changes in this commit include:
- Add a new optional conversion arguments to all of the register_restart_field
routines in SIS_restart.F90.
- Add a new optional scale argument to all of the only_read_restart_field
routines in …

+(*)Write unscaled SIS2 restart files

---

src/SIS2_ice_thm.F90
src/SIS_ctrl_types.F90
src/SIS_dyn_trans.F90
src/SIS_fast_thermo.F90
src/SIS_ice_diags.F90
src/SIS_optics.F90
src/SIS_slow_thermo.F90
src/SIS_state_initialization.F90
src/SIS_sum_output.F90
src/SIS_tracer_registry.F90
src/SIS_types.F90
src/ice_model.F90
src/ice_type.F90

Applied dimensional rescaling to all SIS2 salinity variables.  All answers and
output are bitwise identical.  The specific changes with this commit include:
- Changes to the unit descriptions in the comments for about 58 variables
- Added the new optional argument conc_scale to register_SIS_tracer, mirroring
the corresponding argument in the MOM6 version, to indicate how a tracer
might be unscaled
- Renamed a handful of internal variables or arguments from S to Saln to
help ensure that these variables were being scaled properly
- Added comments noting 4 subroutines that appear not to be used
- Added scale arguments to 6 get_param calls for salinity parameters
- Added scale arguments to 4 MOM_read_data calls for salinities
- Added or modified scale arguments for 4 checksum calls
- Added …

+Rescale SIS2 salinities

---

src/SIS2_ice_thm.F90
src/SIS_ctrl_types.F90
src/SIS_dyn_trans.F90
src/SIS_fast_thermo.F90
src/SIS_ice_diags.F90
src/SIS_optics.F90
src/SIS_slow_thermo.F90
src/SIS_state_initialization.F90
src/SIS_types.F90
src/SIS_utils.F90
src/ice_model.F90
src/ice_spec.F90
src/specified_ice.F90

Applied dimensional rescaling to all SIS2 temperature variables.  All answers
and output are bitwise identical.  The specific changes with this commit
include:
- Changes to the unit descriptions in the comments for about 188 variables
- Renamed a handful of internal variables or arguments from T to Temp to
help ensure that these variables were being scaled properly
- Added scale arguments to 14 get_param calls for temperature parameters
- Added scale arguments to 5 MOM_read_data calls for temperatures
- Added or modified scale arguments for 10 checksum calls
- Added a new element T_0degC to the ice_state_type
- Added a rescaled surface temperature array to pass to update_icebergs
- Removed 12 unused variables and an unnecessary call to calculate_T_Freeze()
- Modified two data_override …

+Rescale SIS2 temperatures

---

src/SIS_dyn_bgrid.F90
src/SIS_dyn_cgrid.F90

Added the new runtime parameters VEL_UNDERFLOW and STRESS_UNDERFLOW to set
minimal values of the velocity and ice-pack lateral stresses that lead to an
underflow of the velocities and stresses to zero.  This new capability can be
needed to give identical results when dimensional consistency tests are carried
out.  Also added the runtime parameter B_DYNAMICS_MIN_MASS to replace a hard
coded value for the B-grid dynamics code.  By default, all answers are bitwise
identical, but there are 2 or 3 new runtime parameters in the SIS_parameter_doc
files.

+Added VEL_UNDERFLOW and STRESS_UNDERFLOW

---

src/ice_ridge.F90

New parameter RIDGE_AREA_UNDERFLOW is introduced in order to avoid the occurrence of undetectably small fractional area and negative ice volume following ridging adjustments from Icepack. The default is 0.0, which does not introduce changes in existing runs.  A reasonable value would be 10^-26 which would correspond to an Angstrom-scale ice patch within a km-scale grid cell.  This addresses #178 and #183

Icepack area underflow patch 

---

src/SIS2_ice_thm.F90
src/ice_model.F90

Removed the unused subroutines and functions estimate_tsurf, enthalpy_from_TS,
enth_melt, e_to_melt_TS, energy_melt_enthS and set_ice_optics, and the archaic
and unused element ocean_fluxes_top in the publicly visible ice_data_type.  All
answers are bitwise identical in any case that compiles, but there are are 7
unused but publicly visible routines and one element of a publicly visible
transparent type that have been eliminated.

+Remove estimate_tsurf and 6 other unused routines

---

src/ice_model.F90

- New code does not compile with -openmp :
ice_model.F90(979): error #6752: Since the OpenMP* DEFAULT(NONE) clause applies, the PRIVATE, SHARED, REDUCTION, FIRSTPRIVATE, or LASTPRIVATE attribute must be explicitly specified for every variable.   [US]
- This PR fixes the issue by adding US as shared

Fixing openmp compilation issue

---

config_src/dynamic_symmetric/SIS2_memory.h

- This allows it to be set at compile time, a feature used by the BGC model.

Updating MAX_FIELDS_ to match MOM6.

---

src/SIS_dyn_cgrid.F90
src/SIS_sum_output.F90

The generic `open_file` call was replaced with the targeted `open_ASCII_file` function, since the generic `open_file` no longer works with the updated FMS2 `open_file` interface in MOM6.

Use open_ASCII_file for sum output

---

docs/zotero.bib
src/SIS2_ice_thm.F90
src/SIS_dyn_cgrid.F90
src/ice_model.F90

- We can't divide by zero, so don't let sigma_i be zero.

Fix for sigma_i going to zero in ITD landfast ice.

---

src/SIS_restart.F90

The legacy `file_type` and `fieldtype` handles for field IO are replaced with the newer MOM IO types (`MOM_infra_file`, `MOM_field`), which provide new FMS-agnostic interfaces to the framework IO.
This also conforms to the new requirement of FMS IO requiring a domain. (Note that this may be relaxed in the future.)
Thanks to Kate Hedstrom (@kshedstrom) for identifying the issue and providing the first draft to this fix.

Update SIS2 to use the new IO interface

---

src/SIS_framework.F90
src/ice_model.F90
src/ice_ridge.F90

The `set_domain` and `nullify_domain` calls used in FMS1 IO now pass through the MOM domain infra.  Explicit references to the internal `mpp_domain` have also been removed.

FMS2: Move FMS domain calls to MOM infra

---

src/SIS_dyn_trans.F90
src/combined_ice_ocean_driver.F90
src/ice_model.F90
src/ice_type.F90

Changes to the combined ice-ocean driver (CIOD) to fix a bug. The state of the ocean is now passed to the ice through the OIB (ocean ice boundary type). A new subroutine has been added to combined_ice_ocean_driver.F90: direct_flux_ocn_to_OIB which is analogous to the existing direct_flux_ice_to_IOB subroutine. The new subroutine assumes the ocean and ice are on the same model grid and that the do_area_weighted_flux option is false for the frazil ice.
This new version of the CIOD requires the OIB as an input when update_slow_ice_and_ocean is called. Currently it is an optional argument, but there is a fatal error if the CIOD is used without it. Therefore, to use the corrected version of the CIOD the call to update_slow_ice_and_ocean in coupler_main must be modified.
The ice_model_init …

Correct interspersed option in the CIOD

---

src/SIS_dyn_cgrid.F90
src/SIS_types.F90
src/ice_model.F90

Removed the code to account for unit rescaling within the SIS2 restart files. This rescaling within the restart files has not been used in the code since the conversion arguments were added to all necessary register_restart_field calls on about June 2, 2022, as a part of PR #175.  The model will still work with older restart files provided that they did not use dimensional rescaling, and even if they did, they can be converted to avoid rescaling with a short run with the older code that created them.  This commit eliminates the publicly visible register_unit_conversion_restarts and rescale_fast_to_slow_restart_fields subroutines, as well as the call to fix_restart_unit_scaling.
Large sections of rescale_ice_state_restart_fields were eliminated, but this routine is still needed to handle …

+Remove rescaling factors from restart files

---

src/ice_model.F90

- Closes issue #199
- Fix ice_layout non-repro of amip using specified ice mode

Fix for specified ice layout non repro issue

---

src/ice_boundary_types.F90
src/ice_model.F90

-This PR is the SIS2 contribution for converting the MOM6 ice-shelf calving flux into new icebergs (this flux is routed through several model components as follows: MOM6 --> coupler --> SIS2 --> icebergs)
-The ice-shelf calving flux is added to FIA%calving through the new subroutine unpack_ocean_ice_boundary_calved_shelf_bergs; this is the ice-shelf equivalent to the existing subroutine
unpack_land_ice_boundary, which adds the frozen discharge from land to  FIA%calving.
-Both styles of calving can occur in the same run (e.g. frozen discharge from Greenland and ice-shelf calving from Antarctica), as long as both calving fluxes are not non-zero in the same cell.
See related changes in:
Coupler: https://github.com/alex-huth/FMScoupler/commit/3e80bbc
MOM6: …

Initialization of point-particle bergs due to ice shelf calving
